n = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(n)))
print('É um número?', n.isnumeric())
print('Só tem espaços?', n.isspace())
print('É alfanumérico?', n.isalnum())